-- init.sql
CREATE TABLE dayStatus (
  id SERIAL PRIMARY KEY,
  day VARCHAR(20) NOT NULL,
  Piano INT NOT NULL,
  Chess INT NOT NULL,
  Japanese INT NOT NULL,
  Programming INT NOT NULL,

  B12 BOOLEAN DEFAULT FALSE,
  OMEGA3 BOOLEAN DEFAULT FALSE,
  Kreatin BOOLEAN DEFAULT FALSE,
  Abwasch BOOLEAN DEFAULT FALSE
);
