name: Scheduled Job

on:
  schedule:
    - cron: '0 22 * * *'  # Every day at 22:00 UTC
  workflow_dispatch:     # Optional: allows manual triggering too

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run a script
        run: |
          echo "Running my app..."
          ./notify/MyNotificationServer
